### ISSUE TITLE
Ruby 2.4.4 will not be built ?

### ISSUE THREAD

**Issue by yujideveloper** [feedforce/ruby-rpm#58]
Ruby 2.4.4 has been released.
https://www.ruby-lang.org/ja/news/2018/03/28/ruby-2-4-4-released/

So, I tried to create pr for Ruby 2.4.4.
However, I can't create pr because `master` branch is already used for Ruby 2.5.x.

Could you create `ruby-2.4` branch as same as `ruby-2.3` and build Ruby 2.4.4.

**Comment by tsub** [comment]
@yujideveloper 

I have created PR https://github.com/feedforce/ruby-rpm/pull/59 for releasing Ruby 2.4.4.

Please wait a moment for the PR to be merged.

**Comment by tsub** [comment]
@yujideveloper 

Ruby 2.4.4 RPM has been released!
https://github.com/feedforce/ruby-rpm/releases/tag/2.4.4

**Comment by yujideveloper** [comment]
@tsub 

Thank you!
